# acode configuration
version: 0.1.0
project:
  name: squareup
  type: generic
  created: 2025-10-31T18:08:33Z

acode:
  version: 0.2.3
  commit: 556082f
  installed: 2025-10-18T19:53:57Z
  ref: main

# AI Assistant settings
assistant:
  model: default
  temperature: 0.7
